"""Instances and profiles.

An instance is a self-contained directory for one game, laid out like Mod Organizer 2::

    <instance>/instance.json    game, paths, Proton and executable settings
    <instance>/mods/<Mod>/      one folder per installed mod, mirroring the Data folder
    <instance>/overwrite/       files created by the game or tools while running
    <instance>/profiles/<P>/    modlist.txt (MO2 format) and plugins.txt per profile
    <instance>/downloads/       archives waiting to be installed
    <instance>/deploy/          deployment manifest and backups of replaced game files
    <instance>/prefix/          default Wine prefix used through umu-launcher
"""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass
from pathlib import Path

from modmanager.core import paths
from modmanager.core.games import GameDef, get_game

INVALID_NAME = re.compile(r'[<>:"/\\|?*\x00-\x1f]')
DEPLOY_METHODS = ("hardlink", "symlink", "copy")


def sanitize_name(name: str) -> str:
    name = INVALID_NAME.sub("_", name).strip().strip(".")
    return name or "Unnamed"


@dataclass
class Executable:
    name: str
    path: str
    args: str = ""
    cwd: str = ""
    use_proton: bool = True

    @classmethod
    def from_dict(cls, d: dict) -> "Executable":
        return cls(
            name=d.get("name", ""),
            path=d.get("path", ""),
            args=d.get("args", ""),
            cwd=d.get("cwd", ""),
            use_proton=d.get("use_proton", True),
        )

    def to_dict(self) -> dict:
        return {
            "name": self.name, "path": self.path, "args": self.args,
            "cwd": self.cwd, "use_proton": self.use_proton,
        }


class Profile:
    MODLIST_HEADER = "# This file was automatically generated by Mod Manager.\n"

    def __init__(self, path: Path):
        self.path = path

    @property
    def name(self) -> str:
        return self.path.name

    @property
    def modlist_file(self) -> Path:
        return self.path / "modlist.txt"

    @property
    def plugins_file(self) -> Path:
        return self.path / "plugins.txt"

    def read_modlist(self) -> list[tuple[str, bool]]:
        """Return ``(mod, enabled)`` pairs from lowest to highest priority.

        ``modlist.txt`` uses Mod Organizer 2's format, where the first line is the
        highest priority mod, ``+`` means enabled, ``-`` disabled and ``*`` unmanaged.
        """
        try:
            lines = self.modlist_file.read_text(encoding="utf-8", errors="replace").splitlines()
        except FileNotFoundError:
            return []
        entries: list[tuple[str, bool]] = []
        for line in lines:
            line = line.rstrip()
            if len(line) < 2 or line[0] not in "+-":
                continue
            entries.append((line[1:], line[0] == "+"))
        entries.reverse()
        return entries

    def write_modlist(self, entries: list[tuple[str, bool]]) -> None:
        body = "".join(("+" if on else "-") + name + "\n" for name, on in reversed(entries))
        paths.write_text(self.modlist_file, self.MODLIST_HEADER + body)


class Instance:
    CONFIG = "instance.json"

    def __init__(self, path: Path, config: dict):
        self.path = path
        self.config = config
        self.game: GameDef = get_game(config["game"])

    # ----------------------------------------------------------------- creation

    @classmethod
    def create(
        cls,
        path: Path,
        name: str,
        game_id: str,
        game_dir: Path,
        data_subdir: str | None = None,
        deploy_method: str = "hardlink",
    ) -> "Instance":
        game = get_game(game_id)
        if (path / cls.CONFIG).exists():
            raise FileExistsError(f"An instance already exists in {path}")
        config = {
            "name": name,
            "game": game_id,
            "game_dir": str(game_dir),
            "data_subdir": game.data_subdir if data_subdir is None else data_subdir,
            "deploy_method": deploy_method,
            "active_profile": "Default",
            "proton": {
                "umu_run": "",
                "prefix": str(path / "prefix"),
                "proton_path": "",
                "game_id": game.umu_id,
                "store": "",
                "env": {},
            },
            "executables": [],
            "selected_executable": 0,
        }
        inst = cls(path, config)
        for d in (inst.mods_dir, inst.overwrite_dir, inst.downloads_dir, inst.deploy_dir):
            d.mkdir(parents=True, exist_ok=True)
        inst.create_profile("Default")
        inst.config["executables"] = [e.to_dict() for e in inst.default_executables()]
        inst.save()
        return inst

    @classmethod
    def load(cls, path: Path) -> "Instance":
        config = paths.read_json(path / cls.CONFIG)
        if not config:
            raise FileNotFoundError(f"No instance found in {path}")
        inst = cls(path, config)
        for d in (inst.mods_dir, inst.overwrite_dir, inst.downloads_dir, inst.deploy_dir):
            d.mkdir(parents=True, exist_ok=True)
        if not inst.profile_names():
            inst.create_profile("Default")
        return inst

    def save(self) -> None:
        paths.write_json(self.path / self.CONFIG, self.config)

    def default_executables(self) -> list[Executable]:
        game_dir = Path(self.config["game_dir"])
        result = []
        if self.game.binary:
            result.append(Executable(self.game.name, str(game_dir / self.game.binary)))
        if self.game.launcher:
            result.append(Executable(f"{self.game.name} Launcher", str(game_dir / self.game.launcher)))
        for label, rel in self.game.extra_executables:
            result.append(Executable(label, str(game_dir / rel)))
        return result

    # -------------------------------------------------------------- properties

    @property
    def name(self) -> str:
        return self.config.get("name") or self.path.name

    @property
    def mods_dir(self) -> Path:
        return self.path / "mods"

    @property
    def overwrite_dir(self) -> Path:
        return self.path / "overwrite"

    @property
    def profiles_dir(self) -> Path:
        return self.path / "profiles"

    @property
    def downloads_dir(self) -> Path:
        return self.path / "downloads"

    @property
    def deploy_dir(self) -> Path:
        return self.path / "deploy"

    @property
    def tmp_dir(self) -> Path:
        return self.path / ".tmp"

    @property
    def game_dir(self) -> Path:
        return Path(self.config["game_dir"])

    @property
    def data_dir(self) -> Path:
        sub = self.config.get("data_subdir", self.game.data_subdir)
        if not sub:
            return self.game_dir
        found = paths.find_child_ci(self.game_dir, sub)
        return found or self.game_dir / sub

    @property
    def deploy_method(self) -> str:
        method = self.config.get("deploy_method", "hardlink")
        return method if method in DEPLOY_METHODS else "hardlink"

    @property
    def proton(self) -> dict:
        return self.config.setdefault("proton", {})

    @property
    def executables(self) -> list[Executable]:
        return [Executable.from_dict(d) for d in self.config.get("executables", [])]

    @executables.setter
    def executables(self, exes: list[Executable]) -> None:
        self.config["executables"] = [e.to_dict() for e in exes]

    # ---------------------------------------------------------------- profiles

    def profile_names(self) -> list[str]:
        if not self.profiles_dir.is_dir():
            return []
        return sorted((p.name for p in self.profiles_dir.iterdir() if p.is_dir()), key=str.lower)

    @property
    def active_profile(self) -> Profile:
        name = self.config.get("active_profile", "Default")
        if name not in self.profile_names():
            names = self.profile_names() or [self.create_profile("Default").name]
            name = names[0]
            self.config["active_profile"] = name
        return Profile(self.profiles_dir / name)

    def set_active_profile(self, name: str) -> None:
        if name not in self.profile_names():
            raise ValueError(f"No such profile: {name}")
        self.config["active_profile"] = name
        self.save()

    def create_profile(self, name: str, copy_from: str | None = None) -> Profile:
        name = sanitize_name(name)
        dest = self.profiles_dir / name
        if dest.exists():
            raise FileExistsError(f"Profile '{name}' already exists")
        if copy_from:
            shutil.copytree(self.profiles_dir / copy_from, dest)
        else:
            dest.mkdir(parents=True)
        return Profile(dest)

    def rename_profile(self, old: str, new: str) -> None:
        new = sanitize_name(new)
        if (self.profiles_dir / new).exists():
            raise FileExistsError(f"Profile '{new}' already exists")
        (self.profiles_dir / old).rename(self.profiles_dir / new)
        if self.config.get("active_profile") == old:
            self.config["active_profile"] = new
            self.save()

    def remove_profile(self, name: str) -> None:
        if len(self.profile_names()) <= 1:
            raise ValueError("Cannot remove the last profile")
        shutil.rmtree(self.profiles_dir / name)
        if self.config.get("active_profile") == name:
            self.config["active_profile"] = self.profile_names()[0]
            self.save()


class InstanceRegistry:
    """Remembers known instances in ``~/.config/modmanager/instances.json``."""

    def __init__(self):
        self.file = paths.config_home() / "instances.json"
        data = paths.read_json(self.file, {}) or {}
        self.instances: dict[str, str] = data.get("instances", {})
        self.last: str | None = data.get("last")

    def save(self) -> None:
        paths.write_json(self.file, {"instances": self.instances, "last": self.last})

    def add(self, inst: Instance) -> None:
        self.instances[inst.name] = str(inst.path)
        self.last = inst.name
        self.save()

    def remove(self, name: str) -> None:
        self.instances.pop(name, None)
        if self.last == name:
            self.last = None
        self.save()

    def valid(self) -> dict[str, Path]:
        return {
            name: Path(p) for name, p in sorted(self.instances.items(), key=lambda kv: kv[0].lower())
            if (Path(p) / Instance.CONFIG).is_file()
        }
